### ISSUE TITLE
Примечание к лабораторной работе Danshina_E_Y

### ISSUE THREAD

**Issue by jskonst** [ISUCT/ISUCT2015_1Course#3]
В целом все хорошо, но :
1. На сколько я знаю Пикачу - собственное имя? и это странно иметь несколько экземпляров одного и того -же? Может стоит назвать класс более общим видом (покемон :) )
2. Если метод называется lightningStrike - то единственное что он должен делать - удар молнией, а внутри оказывается есть варианты :))

**Comment by Allevy** [comment]
Работа была исправлена) Заменила на покемонов, как вы и написали, с разными вариантами, а так же чутка изменила выводимые параметры, более подходящие под то, что я выбрала) И поправила метод, в соответствии с Вашим замечанием)

**Comment by jskonst** [comment]
Вот так сильно лучше :)
